name: PHP Security Checker

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
    CodeScan:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v2
              id: cache-db
              with:
                  path: ~/.symfony/cache
                  key: db
            - uses: symfonycorp/security-checker-action@v2
              with:
                  lock: app/composer.lock
#                  disable-exit-code: 1
#            - name: Display the vulnerabilities as JSON
#              run: echo ${{ steps.security-check.outputs.vulns }}
